### ISSUE TITLE
What are the best ways to sync VC's among multiple devices 

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#213]
Dear Team,

What could be the best suggested approach by which anyone should approach to sync the VC's on multiple devices for a solution using DAF.

**Comment by devrajsinghrawat** [comment]
Along with VC what approach should be taken to sync DID, Keeping the risk that if we are exporting the PK then there could be security risk too..

**Comment by mirceanis** [comment]
1. Controlling the DID (the ability to modify the DID document).
In the case of ethr-did, normally, this means having access to the same keys on every user device. This is the only option that would work out of the box at this point with DAF.
To have more advanced mechanism of control (like using a multisig proxy contract) a plugin similar to `daf-ethr-did` would have to be written.
For other DID methods this control may differ (for example, web-did requires control of a web domain which is not device specific).

2. The credentials/claims/etc.
To be able to do this across multiple devices, you would need a synchronization mechanism. There is no generic mechanism that we can recommend at this point(at least not one that directly plugs into DAF).
At uPort we have used our [caleuche-service](https://github.com/uport-project/lambda-caleuche) in the past to do backup of e2e encrypted data, but it is not a real sync mechanism.

There are solutions out there that solve this for generic data, so we are making efforts to enable DAF to use these as the storage layer. The next major version of DAF tries to abstract the storage layer so that plugins to support other databases, perhaps distributed databases, can be used.

3. Using a remote agent. This method requires a DAF agent to run on a server and have complete control of the credentials and keys, and then give access to every user device to control this agent. The next major release of DAF should make this possible.
But, this is a centralized solution, so it doesn't work for all situations.
