### ISSUE TITLE
regarding securing the of VC's from impersonation 

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#220]
Dear @simonas-notcat @mirceanis 

Hope you are doing great.

If my understanding is correct then whenever we share the VC/VC's against any SDR from a Service provider then we need to mandatorily wrap it in a VP and then sign on that VP so that service provider should be sure that this VC/VC's were sent by me only and not any any-other person or service who might have stored to my attested VC (JWT) and trying to impersonate me.

Kindly confirm if this is the way we avoid a Man in the Middle and our leaked VC's attack.

Q 2 : What will happen if a SP will receive a VC directly instead of VP? will DAF allows such request to process or DAF makes this check on DIDComm level itself while transmitting the credentials

**Comment by mirceanis** [comment]
The selective disclosure flow that exists in DAF is based on the existing [uPort selective disclosure flow](https://developer.uport.me/flows/selectivedisclosure) with the messages adapted to fit into the W3C VC/VP paradigm.
Unfortunately this is not a community standard so a lot of the burden of securing this falls on the implementer.
Also, those protocols don't make any assumptions about the subject of all the credentials,( mostly because some credentials may need to be paired or chained to be able to form a complete proof in some situations).

DAF will, by default, process messages that contain VCs/VPs regardless of the protocol they are coming from.
If this is the result of a selective disclosure response, then the app receiving the response will have to verify this and enforce the security precautions that you asked about.
It is this app that will have to make this check about the origin or subject of the credentials. This check is not performed by DAF.

The longer term plan is to create a DAF plugin that adds support for the [presentation-exchange](https://identity.foundation/presentation-exchange/) protocol which should provide some of these checks out of the box.

**Comment by mirceanis** [comment]
I'm closing this; please reopen if the answer does not suffice
